### ISSUE TITLE
look into github pages directory changes

### ISSUE THREAD

**Issue by richardrissanen** [meetyourdeveloper/meetyourdeveloper.com#5]

**Comment by richardrissanen** [comment]
https://github.com/blog/2228-simpler-github-pages-publishing

Discloses the publishing options for github pages.

> 1. Selecting master branch will publish your site from the master branch. This is useful for repositories dedicated to website content.

> 2. Selecting master branch /docs folder will publish from the /docs folder of your master branch. This lets you maintain documentation and code together on one branch, and open source maintainers can accept contributions for both in a single pull request.

https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch

Discloses in detail how to implement what I believe to be the ideal scenario considering the options

**Comment by jarrodtaylor** [comment]
Moved everything to `docs/`. The Github docs say to point a CNAME and/or A record at meetyourdeveloper.github.io, but that won't be the case for this.

**Comment by richardrissanen** [comment]
Moved to Heroku!
